[book]
authors = ["hinto-janai"]
language = "en"
multilingual = false
src = "src"
title = "`mw` user-book"
git-repository-url = "https://github.com/hinto-janai/mw"

[preprocessor.last-changed]
command = "mdbook-last-changed"
renderer = ["html"]

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/hinto-janai/mw"
additional-css = ["last-changed.css"]
